dist: trusty
sudo: required

language: node_js
node_js:
  - 10
  
branches:
  only:
  - master

before_script:
  - export DISPLAY=:99.0
  - /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -y curl build-essential supervisor wget
  - wget http://es.archive.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.12_amd64.deb
  - sudo dpkg -i libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb

install:
  - npm ci

script:
  - npm run test