dist: trusty
sudo: required

language: node_js
node_js:
  - 10
  
branches:
  only:
  - master

before_script:
  - export DISPLAY=:99.0
  - /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

install:
  - npm ci

script:
  - npm run test